services:
  - type: web
    name: avify-api
    env: node
    plan: free
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
